### PR TITLE
Translate Cartoon Cartoon Summer Resort Episode 2 to pt-BR

### PR DESCRIPTION
**Pull request by MateusRodCosta**
The pt-BR version of CCSR 2 is currently lost media. This attempts to translate it to pt-BR by first reusing the pt-BR strings from the other episodes (either intentionally shared or acidentally left in) and fill out the remaining strings with new translations.

---

I will run this translation through a friend of mine who works and agreed do proof-read it.
After that I will be able to merge it.

### CODE REVIEW

**Comment by MateusRodCosta** [comment]
This translation should be good enough for inclusion now.
I had that translator friend proofread and made a few tweaks.

Only thing missing would be trying to re-use the graphic assets from the other episodes where possible and I guess this would be done.

The other episodes could also have their translations improved, but I think that would be low priority.

Also interestingly I tried to host the second revision of the translation but apparently it gets ignored on my browser for some reason when served from GH Pages. But it works fine serving via npm.

**Comment by mattbruv** [comment]
There are some graphics that we can't re-use that are specific to episode 2 that we would need translations for. The other translations (the mayor, courage, etc.) we can grab from other episodes.

For these I just need the PT translations for each, don't worry about changing the graphics. I have PSD files in the other folders that I can just edit, I just need something to put. 

* [summer.instructs.02.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/Internal/summer.instructs.02.png) (I can probably just re-use [this image](https://github.com/MateusRodCosta/ccsr/blob/ccsr-2-br/port/translations/1/pt/images/summer.instructs.01.png) and replace tio gus with Longhorn)
* The [title image](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/Internal/title.png) from the main UI.
* [block.51.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.51.face.png)
* [block.121.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.121.face.png)
* [block.122.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.122.face.png)
* [block.131.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.131.face.png)
* [block.132.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.132.face.png)
* [block.133.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.133.face.png)
* [block.134.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.134.face.png)
* [block.135.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.135.face.png)
* [block.136.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.136.face.png)
* [exit.tennis.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/end.sequence/exit.tennis.png)
* [2end.message.lose.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/end.sequence/2end.message.lose.png)
* [2end.message.win.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/end.sequence/2end.message.win.png)

**Comment by MateusRodCosta** [comment]
> There are some graphics that we can't re-use that are specific to episode 2 that we would need translations for. The other translations (the mayor, courage, etc.) we can grab from other episodes.
> 
> For these I just need the PT translations for each, don't worry about changing the graphics. I have PSD files in the other folders that I can just edit, I just need something to put.

> * [summer.instructs.02.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/Internal/summer.instructs.02.png) (I can probably just re-use [this image](https://github.com/MateusRodCosta/ccsr/blob/ccsr-2-br/port/translations/1/pt/images/summer.instructs.01.png) and replace tio gus with Longhorn)

Yeah, it's basically the same text only changing the character name.
Please, translate the character name as "Cabelão", the dub for the pilot for his show is lost but that should be a good enough translation for "Longhair". Also please use "o Cabelão" if it's used in a place that would required a gendered article.

> * The [title image](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/Internal/title.png) from the main UI.

Re-use the same "Cartoon Cartoon Summer Resort" logo from the other games, set the character name to "Cabelão.
From [the Web archive](https://web.archive.org/web/20031204034922/http://www.cartoonnetwork.com.br:80/play/tennis_menace/index.html), the official name of the game was "A Ameaça do Tênis" (so if you are going to make something similar to the en UI, it will likely be two block "A Ameaça" and "do Tênis").
Re-use the Loading text from the other games, if possible.

> * [block.51.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.51.face.png)

"Armadura"

> * [block.121.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.121.face.png)

"Estrela-do-mar"

> * [block.122.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.122.face.png)

"Polvo"

> * [block.131.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.131.face.png)

"Uma flor"

> * [block.132.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.132.face.png)

"Bigode Falso"

> * [block.133.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.133.face.png)

"Pedra de estimação"

> * [block.134.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.134.face.png)

"Nabo"

> * [block.135.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.135.face.png)

"Carteira"

> * [block.136.face.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/map.visuals/block.136.face.png)

"Gatinho de pelúcia"

> * [exit.tennis.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/end.sequence/exit.tennis.png)

"Sair da quadra de tênis"

> * [2end.message.lose.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/end.sequence/2end.message.lose.png)

"Oh, não!!!

O Dexter não conseguiu deter os canhões de bola de tênis do robô!
Encontre mais items ou use items diferentes da próxima vez"

> * [2end.message.win.png](https://github.com/mattbruv/ccsr-source/blob/9cf77344e5d6505412e04cd3893737f7f614ff81/2/end.sequence/2end.message.win.png)

"Vitória!!!

Você ajudou o Dexter a parar o robô descontrolado!
Agora todo mundo pode jogar tênis em paz!"

---

When you finish this, please ping me. AFAIK there are still some mistakes in the translation, so it should be nice for me to do a new round of translation QA before fully merging.

**Comment by MateusRodCosta** [comment]
> Re-use the same "Cartoon Cartoon Summer Resort" logo from the other games

Small correction and clarification: use the same "Balneário de Verão do Cartoon Cartoon" logo from the other pt-BR translations

**Comment by mattbruv** [comment]
@MateusRodCosta I just added all of the image translations to this branch. I also removed the loading text which was in the other title images, among a few other things. It should be good for you to test now, just remember to re-run `setup.py`. Also, if you need a guide for Episode 2 to know where everything is located and how it progresses, you can reference [this graph.](https://github.com/mattbruv/ccsr/blob/main/port/images/ep2graph.png)

**Comment by MateusRodCosta** [comment]
I made some small tweaks to the translation.

There are a few mistakes still though. In pt-BR we don't have inverted exclamations or interrogations, sot hat should be removed from the end game messages.
There's also a typo on the win message, it has "pararo" written instead of "parar o". And one on the lose message where it says "bolade" instead of "bola de".

I didn't take note of all characters to make sure they are all translated, but I did notice 2 of them missing a proper translation: Blossom ("Florzinha") and Bubbles ("Lindinha").

**Pull request merged**
